### PR TITLE
WW II Factions

### PR DESCRIPTION
**Pull request by MatrikSky**
**Those are four new WW2 factions including Germany and UK. In the future I will be making new factions such as USSR and US, for now i official announce that those two factions are 100% complete. They work fine with only two small bugs that I encountered, while play-testing them. Sorry to say but the small amount of time that I have (because of High School ) will delay the progress on USSR (around 16% complete) and US (haven't even started) factions.**

**- WW2_Heer,**
//Done
//Still has some other bugs #306
**- WW2_Heer (Police),**
//Done
//Still has some bugs #306
**- WW2_UK,**
//Done
//Still has some bugs #306
**- WW2_UK (Police),**
//Done
//Still has some bugs #306

**WW II factions will need a couple of mods so I have made a collection just for you.**
https://steamcommunity.com/sharedfiles/filedetails/?id=1980236949

Factions made by **MatrikSky**

### CODE REVIEW

**Comment by billw2012** [comment]
So this still needs some work, there are vanilla vics spawning (as you noted), and the police appear to just be military, which doesn't really fit the scenario (they are meant to be civilian police, not military police).

**Comment by MatrikSky** [comment]
I have fixed the error where military spawned instead of police. And the only problem left is the vanilla vics and guns spawning but that is not a bug on my side.

**Comment by MatrikSky** [comment]
If you mean that the military is police, not the bug that i mentoned sometime erlier. I simply don't have any ww2 police uniforms or vest so I used german SS instead of Wermacht for the police aswel british military for uk police.

**Comment by billw2012** [comment]
> I have fixed the error where military spawned instead of police. And the only problem left is the vanilla vics and guns spawning but that is not a bug on my side.

I think it is, you are copying the default template then partially replacing some of it. You need to specify explicitly all the required items, you can't skip some. Check `Templates\initCategories.sqf` for what is required and what isn't. This may not be entirely correct as I couldn't get Sparker to confirm it before he left, so its just my guess. If there isn't something thats an exact match then just put in what you would prefer to spawn in its place. e.g. MRAP can just spawn a car of some kind.

**Comment by MatrikSky** [comment]
Yep I will try to do that today. Still, I think the MXs and Carrier Vest spawning in vics isn't on my side since I noticed that some people completed that those weapons spawn with different factions.

**Comment by billw2012** [comment]
> Yep I will try to do that today. Still, I think the MXs and Carrier Vest spawning in vics isn't on my side since I noticed that some people complained that those weapons spawn with different factions.

Sure yeah we still have some things to fix with item spawning definitely!

**Comment by billw2012** [comment]
That last change is very broken. Vic weights array must match and you missed a square bracket. Please make a new PR for the WW2 Civ vics and I can merge it when we have a system in place for selecting between them.

**Pull request closed without merging**
