### PR TITLE
Lingor Island Map Markup

### PR DESCRIPTION
**Pull request by H-Finch-404**
Should be mostly error free, I triple-checked every location sector module.

Contains lots of airports featured on the island, although not all of them because there are simply too many.

Pathing on the big NE bridge seems to work with help of the bridge connections. They do sometimes crash into the lamps, but they quickly recover and move on.

### CODE REVIEW

**Comment by Sparker95** [comment]
Thanks Finch! I will try to check the map ASAP.

**Comment by Sparker95** [comment]
Hi,

when I launch the mission I see lots of messages about objects getting destroyed. Most of them are Huron containers we use for markup. I guess they clip into something and get killed, probably they also fly into orbit. You shoud disable simulation on all of them. In fact I try to disable simulation on all markup vehicles to avoid this, but it's not documented.

Here's the full list:
```
00:13:39 [NoClass.fnc] INFO: EH_Killed: [18d5a460b80# 95630: ammostore2.p3d,<NULL-object>,<NULL-object>,false] at [6098.93,9544.19,0]
00:13:39 [NoClass.fnc] INFO: EH_Killed: [18d5a402080# 95651: mil_barracks.p3d,<NULL-object>,<NULL-object>,false] at [6063.81,9531.87,1.90735e-006]
00:13:39 [NoClass.fnc] INFO: EH_Killed: [18d5a460100# 96683: mil_barracks_i.p3d,<NULL-object>,<NULL-object>,false] at [6104.98,9525.91,-0.000427246]
00:13:39 [NoClass.fnc] INFO: EH_Killed: [18d5a401600# 95652: mil_barracks.p3d,<NULL-object>,<NULL-object>,false] at [6071.28,9520.04,1.90735e-006]
00:13:39 [NoClass.fnc] INFO: EH_Killed: [18d5a403580# 95629: posed.p3d,<NULL-object>,<NULL-object>,false] at [6077.1,9547.13,1.71661e-005]
00:13:39 [NoClass.fnc] INFO: EH_Killed: [18d5a400100# 96667: posed.p3d,<NULL-object>,<NULL-object>,false] at [6126.15,9542.92,1.90735e-005]
00:13:39 [NoClass.fnc] INFO: EH_Killed: [18d329d8100# 95665: posed.p3d,<NULL-object>,<NULL-object>,false] at [6074.98,9501.56,0.00178909]
00:13:39 [NoClass.fnc] INFO: EH_Killed: [18d5a462080# 96668: garaz_bez_tanku.p3d,<NULL-object>,<NULL-object>,false] at [6109.15,9550.2,-0.000159264]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18def514b80# 900385: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [7476.9,1727.28,-4.76837e-007]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18e01134b80# 899686: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [2733.33,6652.12,-1.90735e-006]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18e3900e080# 899085: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [4240.47,7455.94,0.000879288]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18df7d26080# 898617: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [6997.25,9339.01,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18dccb28100# 898887: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [5502.7,5010.41,-9.53674e-007]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18df32e2b00# 899208: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [644.584,1000.85,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18df6df5600# 900925: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [6096.97,1714.4,-9.53674e-007]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18debcfa080# 900930: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [6092.18,1766.73,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18e38c25600# 900390: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [7481.03,1715.27,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18debdde080# 899182: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [3540.04,3722.94,-1.52588e-005]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18df32c3580# 899213: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [647.737,1005.79,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18e38ff5600# 899381: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [1990.49,1072.25,9.53674e-007]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18e069a4b80# 898856: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [6075.04,9018.37,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18e38cb8100# 901630: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [9216.43,8250.61,-0.0031395]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18df4722080# 900703: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [706.319,9935.37,4.76837e-007]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18d349f4100# 898948: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [5841.23,4010.85,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18df8070b80# 899945: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [5926.92,6746.62,-9.53674e-007]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18df1edc100# 899940: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [5958.77,6746.92,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18e07304b80# 899921: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [6137.87,6793.35,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18e38df6080# 899386: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [2006.55,1071.95,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18e05cfb580# 900651: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [4153.78,1585.36,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18df3331600# 900871: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [3114.47,7982.53,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18e4179c100# 899681: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [2921.05,6462.54,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18df7bd1600# 899447: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [1770.53,8189.88,-4.76837e-007]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18dff449600# 899950: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [5904.43,6746.21,-9.53674e-007]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18dfb205600# 900698: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [751.151,9960.75,4.76837e-007]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18df40b5600# 899413: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [880.032,7667.27,-0.00268364]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18df3c6a080# 899452: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [1756.87,8182.43,0.131986]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18dfa66a080# 899418: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [845.029,7664.68,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18df3344b80# 900866: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [2985.32,8007.67,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18e010e2080# 901149: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [1964.79,4537.06,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18e05e00100# 900091: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [5818.81,6794.14,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18df7df4100# 899916: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [6133.73,6784.29,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18df1026b00# 899525: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [5645.72,9570.86,-8.4877e-005]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18dfd847580# 899706: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [2683.27,6692.65,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18d34a1e080# 899696: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [2693.35,6692,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18e05cf8100# 900656: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [4182.65,1558.26,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18df8378100# 899100: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [4180.79,7491.68,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18d34a39600# 899691: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [2730.55,6631.97,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18df4702b00# 900708: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [671.124,9939.31,4.76837e-007]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18e05e03580# 900086: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [5818.88,6784.63,9.53674e-007]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18dfda8f580# 900940: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [6097.7,1766.21,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18d34a0ab00# 899701: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [2920.48,6490.8,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18dfdab2b00# 900935: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [6036.37,1723.28,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18e010b3580# 901159: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [1998.74,4551.52,-0.29]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18debdbeb00# 899187: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [3535.93,3737.29,-0.00268555]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18df6ef4b80# 899105: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [4217.12,7439.88,-0.00229073]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18df837b580# 899095: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [4186.33,7482.83,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18e38bfa080# 900401: stan_east_ep1.p3d,<NULL-object>,<NULL-object>,true] at [7515.39,1749.22,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18dff808100# 898507: stan_east_ep1.p3d,<NULL-object>,<NULL-object>,true] at [6981.09,9362.62,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18e012cb580# 898919: camonet_nato_var1.p3d,<NULL-object>,<NULL-object>,true] at [5943.7,4051.24,0.000665665]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18e05130b80# 900556: camonet_nato.p3d,<NULL-object>,<NULL-object>,true] at [4173.07,1447.27,0]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18dff538100# 898881: slingload_01_cargo_f.p3d,<NULL-object>,<NULL-object>,true] at [5493.39,5016.71,0.0624189]
00:13:42 [NoClass.fnc] INFO: EH_Killed: [18dfb3f4b80# 899272: barels.p3d,<NULL-object>,<NULL-object>,true] at [649.036,1001.72,-3.8147e-006]
00:13:46 [NoClass.fnc] INFO: EH_Killed: [18df801cb80# 898824: loudspeakers_f.p3d,<NULL-object>,<NULL-object>,true] at [6074.11,9014.93,0.00100231]
```

**Comment by H-Finch-404** [comment]
Thanks for the response! If I disable the simulation on the markup objects like vehicles and ammoboxes it should be fine right?

**Comment by Sparker95** [comment]
> 
> 
> Thanks for the response! If I disable the simulation on the markup objects like vehicles and ammoboxes it should be fine right?

Yes it will be fine. It's better to do this even if vehicles are placed on terrain away from objects. Sometimes they clip through terrain a little bit which causes them to be launched into space.

**Comment by H-Finch-404** [comment]
I disabled simulation on hemtt transport and the huron cargo containers, let me know if the killed eh still spam :D

**Comment by Sparker95** [comment]
Thanks, I'll try to check it at the end of this week.

**Pull request merged**
