### PR TITLE
Damage persistence for units

### PR DESCRIPTION
**Pull request by SomethingSimpl**
Tested by teleporting to a garrison, damaging vehicle, letting garrison despawn by teleporting away, spawning garrison in by teleporting in - vehicle remained damaged
After that, saved state, restarted mission, loaded state, vehicle remained damaged correctly.

Anything else that would need to be checked?

Atm this checks every "unit" in garrison, infantry included - so infantry also gets persistent wounds, not sure if desired going forward.

### CODE REVIEW

**Comment by MatrikSky** [comment]
That's a really nice addition to the game. 😺 👍

**Comment by Sparker95** [comment]
Hi!

That's a good addition overall, and it seems to be well written too.

Now about the problems:
- I think that infantry should be excluded from this.
- It will make management of player's vehicles a bit harder, since currently there is no proper way to repair a vehicle. But maybe we can leave it like this? I am not sure.

**Comment by SomethingSimpl** [comment]
Hi,

Glad you checked it out!

For the first point - sure I can exclude them, I just liked the feeling of revisiting a base I unsuccessfully attacked and seeing some soldiers limping around etc. Adds to the immersion/ambiance a bit. I left it this way because you guys went all the way and kept  the units at bases persistently (and thats awesome!) so it was a logical step for me.
Maybe if we could work out some orders for inf to heal at some points so that they dont stay permanently damaged? Not sure if thats already done/happens in vanilla or how complex that would be.

For the second point yeah - its more of a being used to ACE3 and their logistics systems and repairing cars with toolkits. Maybe I could whip up a function and make a buildable repair station for vanilla? You could place the building through buildUI, assign an action to it, select a vehicle and repair it (most likely fully to not be so complex). How would that sound? Also I saw an action for the garrison called - ActionGarrisonRepairAllVehicles. Is that used? Because another issue could be that you would just damage the AIs vehicles and they would never get new ones/repair old ones.

**Comment by SomethingSimpl** [comment]
Tested everything on hosted(non dedicated) server and fully works - the damage syncs up across clients correctly.

**Comment by Sparker95** [comment]
> I saw an action for the garrison called - ActionGarrisonRepairAllVehicles. Is that used? 
Yes, bots can repair their vehicles if they are damaged.

It would be very nice if you could add a buildable repair station. I guess you can just copy the way we implemented the medical tent for now.

**Comment by SomethingSimpl** [comment]
We can close this without merge as I made another push with proper changes.

**Pull request closed without merging**
