### PR TITLE
Update stringtable.xml

### PR DESCRIPTION
**Pull request by MJVEVERUSKA**
Hello. Everything tested on the server

### CODE REVIEW

**Comment by Sparker95** [comment]
Hi! Thanks a lot for provided translation!
Will merge it before next release.

**Comment by Sparker95** [comment]
Hi! I've just merged another commit which added Polish translations. Could you resolve the merge conflicts please?

**Comment by MJVEVERUSKA** [comment]
Ok.

Dne út 30. 6. 2020 19:23 uživatel Saveliy Tronza <notifications@github.com>
napsal:

**Comment by MJVEVERUSKA** [comment]
Resolved - fixed

**Comment by Sparker95** [comment]
I wanted to checkout this branch at your repository but couldn't, it said that it's either private or deleted. Any ideas?

**Comment by Sparker95** [comment]
I honestly don't know how to merge it properly at this point, I am not a Git expert.

There are several conflicts.

    First of all, many people have contributed to the stringtable file, and many people editing same file at same line numbers cause Git conflicts.
    Second problem is that I have renamed Vindicta.Altis folder to src, and we have a slightly different folder structure now, which is another source of conflict.

I'd suggest you to update your fork with our development branch and make a new pull request. Or perhaps wait till there is more text to translate.

I am very sorry for inconvenience!

**Comment by Sparker95** [comment]
Since we've merged the other one, this can be closed.

**Pull request closed without merging**
