### PR TITLE
Add Southern Sahrani map

### PR DESCRIPTION
**Pull request by LukisBrans**
Some problems with the PD buildings, some of them on the map are stuck in moutains or duplicated so we can't get inside.

### CODE REVIEW

**Comment by Sparker95** [comment]
We need to think what to do with those. Any ideas?

**Comment by Sparker95** [comment]
Also, thanks for your contribution!

**Comment by LukisBrans** [comment]
For the problem of PD buildings : if we found a bulding with no access, we can remove it from the editor, but I don't know if it works

**Comment by Sparker95** [comment]
I've checked it and it seems to run. Thanks!

**Pull request merged**
