### PR TITLE
Adding github actions (thx ace team)

### PR DESCRIPTION
**Pull request by zalexki**
Remove CircleCI and appveyor configs to regroup everything under github actions

Next steps will be draft release and CD (auto publish to workshop)

### CODE REVIEW

**Comment by zalexki** [comment]
@billw2012 i don't know how to remove the appveyor from the list i guess @Sparker95 need to remove them in the github configuration of the project somewhere ?

Also @Sparker95, i think https://github.com/marketplace/actions/release-drafter can help you for release.

**Comment by Sparker95** [comment]
That's cool, thanks a lot Sen!

**Comment by Sparker95** [comment]
I guess you can merge it when you can

**Comment by zalexki** [comment]
i've added again the appveyor let's run both for some time.

@Sparker95 i've also added release drafter so, as i understand, next time you will merge into master there will be a draft release with some changelogs ready for you to use

**Comment by Sparker95** [comment]
So... what's up with merging this @zalexki ? Am I right that it will only start using the Github actions after we have merged this?

**Comment by zalexki** [comment]
@Sparker95 hum i was waiting for approvals with a review but i guess we never used it here ?

**Comment by Sparker95** [comment]
I can't review what I don't understand, and I don't understand CI things. I see it works and gives same results as appveyor CI we had, so it's allright I guess.

**Comment by zalexki** [comment]
ye ok it was more about all the files that i delete to make sure we don't use them

**Comment by Sparker95** [comment]
I see you removed sqf-validate, we never used it really. SQF-VM does all that.

**Comment by zalexki** [comment]
ye i think most of my clean is ace tools that we never used, merging then. 
thx @Sparker95

**Pull request merged**
