### PR TITLE
Improve camps build ui changes

### PR DESCRIPTION
**Pull request by Sparker95**

### CODE REVIEW

**Comment by Sparker95** [comment]
Now I wonder, what is this @marvis999 ?

**Comment by marvis999** [comment]
I made a backup of:

- Project_0.Altis/UI/BuildUI/BuildUI.h
- Project_0.Altis/UI/BuildUI/BuildUI.sqf
- Project_0.Altis/UI/BuildUI/BuildUI_Macros.h 

I think those changes might be good if you didn't change any of those files in the meantime. I'll check in detail later. Don't know if the commits you made are still good?

definitely don't want to merge this, I think:

- Project_0.Altis/JeroenArsenal/JNA/fn_arsenal_init.sqf
- Project_0.Altis/UI/ClientMapUI/Controls/IntelPanel.h
- Project_0.Altis/UI/Resources/MissionUIControlClasses.h
- Project_0.Altis/UI/Resources/UIProfileColors.h 
- Project_0.Altis/description.ext
- Project_0.Altis/init.sqf

**Comment by Sparker95** [comment]
Hey, I have just had a look, my commits are not useful at all any more. I don't remember why I added them to your branch.

**Comment by Sparker95** [comment]
Closing it for now. You said you have backed up your changes. Branch will stay I guess.

**Pull request closed without merging**
