### PR TITLE
General Faction Changes

### PR DESCRIPTION
**Pull request by MatrikSky**

### CODE REVIEW

**Comment by Sparker95** [comment]
Could you resolve the conflicts? Also, you are not removing UK faction, right?

**Comment by MatrikSky** [comment]
> Could you resolve the conflicts? Also, you are not removing UK faction, right?

Yep, I will resolve it in a minute and I'll remove ww2 UK. I just need to make a local copy of it.

**Comment by Sparker95** [comment]
I mean I wasn't sure if you were also removing UK or you omitted its removal by mistake. It's up to you.

**Comment by MatrikSky** [comment]
I removed ww2 UK I meant to remove it in the first place, but I was holding it a bit longer for no particular reason. Also, I resolved the conflict.

**Comment by Sparker95** [comment]
Ok I merged it, but I will not upload this one to Steam.

**Pull request merged**
