### PR TITLE
Additional NATO Aligned LDF 2017 Faction

### PR DESCRIPTION
**Pull request by Straker27**
Adds a fictional LDF NATO 2017 faction more closely aligned with NATO. Essentially a fictional Baltic state with NATO personal equipment and light vehicles but with older Warsaw Pact / Former Yugoslavian heavy equipment. 

To be honest the armoured vehicles and aircraft are a bit of a kludge until we are able to define vehicle and aircraft load-outs along with appearance attributes as part of the template files so they all appear to be from one faction. 

- Personal equipment is the main equipment purchased by Livonian forces (a result of the desire to be NATO compatible on foreign deployments.) Reconnaissance forces are lavishly equipped to comparible NATO standards having been trained by both American and European special forces.

- Despite the developing insurgency vehicles and other heavy equipment are a mixture of those supplied as surplus by friendly NATO nations or ageing equipment left over from the pre-NATO period.

- Aircraft are a mix of modern cheaper counter insurgency craft purchased due to the developing insurgency and surplus equipment bought from neighbouring countries as they themselves buy newer aircraft.

- The Livionian Police Service is a well equipped force due to the level of armed criminality imported from other countries further east but struggling in the developing insurgency.

### CODE REVIEW

**Comment by Straker27** [comment]
So I think I've manged to hunt down the last few issues with this if anyone else would like to have a look that would be great. 

Otherwise I think this is fairly good to commit at an alpha level. Without further play-testing by others I can't see myself finding any other issues easily.

**Comment by Sparker95** [comment]
That's cool, thanks a lot! Even passes validation!
I will check it when I will be integrating other factions by other guys.

**Comment by Straker27** [comment]
I'll have a quick look through and try and cull the ACE items (I think it is probably some of the grenades.)

**Comment by Straker27** [comment]
I've updated the faction information to follow the new format with additional checks but will leave this as is. 

It will not pass the additional checks without conflicts being resolved by someone with write access. Although it would seem likely that it should be able to pass them in terms of the faction and loadout configs themselves.

**Comment by Sparker95** [comment]
Don't worry about conflicts, I will pick it up from here (:

**Pull request merged**
