### PR TITLE
Updated Altis Map

### PR DESCRIPTION
**Pull request by MatrikSky**
Added missing outposts, factories, power plants (as outposts) and villages. I redid every location to look a lot nicer. It's up to you if you chose to use this.

### CODE REVIEW

**Comment by marvis999** [comment]
Looked over it and found now problems, but I think it needs testing. My understanding is that editor placed objects tend to degrade performance. 

Playtest on the server?

**Comment by billw2012** [comment]
Also useful to know, does this break saves? My guess is that it would.

**Comment by MatrikSky** [comment]
We just need to test it with a couple of players to see the fps, if it's low I can always cut some objects. When I tested it myself everything worked well.

**Comment by MatrikSky** [comment]
> Also useful to know, does this break saves?

Yep I think that it will brake saves for 100% so before release it would need to be announced so community can make a copy of old vindicta version and play on their current save.

**Comment by Sparker95** [comment]
Why? I think it won't break anything. People will just have old locations with their old saved games. But I didn't check the new .sqm file yet so can't tell exactly.

**Comment by billw2012** [comment]
Yeah what I meant was, please check IF this breaks save game!

**Comment by MatrikSky** [comment]
Checked if it works and it did. It loaded without any errors only think that I have seen is vehicles spawning on their last positions which sometimes end up in walls, and then they explode same for the crates.

**Comment by billw2012** [comment]
Cool, weird though our spawning should fix up vehicle positions I thought, checking for collision?

**Comment by MatrikSky** [comment]
This is how a truck spawned after loading save on new map
https://imgur.com/a/ODpmwso

**Comment by MatrikSky** [comment]
And new location aren't added as outpost until you restart the mission but I get it why.
https://imgur.com/a/50LbXFT

**Comment by MatrikSky** [comment]
Oh, ad we have shit like that XD
https://imgur.com/a/3ISZ4UI

**Pull request closed without merging**
