### PR TITLE
Merge arsenals action.

### PR DESCRIPTION
**Pull request by billw2012**

### CODE REVIEW

**Comment by billw2012** [comment]
Yeah it occurred to me as well last night. It would mean you couldn't load from the inventory of another arsenal object but I guess that is fine. I want to add some clearer onscreen instructions for these load/unload things as I noticed some people are confused and thing e.g. that you can only load the inventory of the arsenal itself into the arsenal. I will use hint or cutscene text to give a quick explanation.

**Comment by Sparker95** [comment]
Sorry can't check it right now. Can you describe how it works? The old 'external inventory to this arsenal' button now also moves items from another arsenal, right?

**Comment by Sparker95** [comment]
Anyway, I'm not the master of the Arsenal code, so if Jeroen approves, I think it's ok.

**Comment by billw2012** [comment]
Yeah now in "Inventory to Arsenal" it detects if its an arsenal object, if it is then it just moves it all (kicking all players out of both arsenals to maintain coherence without fiddly update code). Also I added the modifier keys and an onscreen hint for them when using "Arsenal to Inventory" so you can do Shift click for +5, Ctrl click for +10 and Shift Ctrl click for +100 (respecting inventory size of course).
I will extend range for the actions and then merge it.

**Pull request merged**
