### PR TITLE
Process text to be Localizable

### PR DESCRIPTION
**Pull request by nercon**
Convert commonPhrases.sqf dialogues to be localizable
Convert DialogueCivilian.sqf dialogues to be localizable
Convert DialoguePolice.sqf dialogues to be localizable
Localized a few dialogues to Chinese simplified for testing purpose
Delete a duplicated dialogue from _phrasesIntelSource, DialogueCivilian.sqf
Unified dialogues sharing the same line: "STR_NODE_C_ANYMORE", "STR_NODE_P_BYE", "STR_NODE_P_THANKS" "STR_NODE_C_GATHER_*", "STR_NODE_C_INFO_INTRO_5"

### CODE REVIEW

**Comment by nercon** [comment]
Update with most files localizable now. It is in a decent stage but needs more testing to make sure I didn't break any code while carrying them over.
I'll need to go into the actual game in order to discover those hard to find localizable strings.

**Comment by nercon** [comment]
As of now, I'd say 99% of the in-mission texts are localizable and localized into Chinesesimp, the remaining 1% are the ones that I  potentially missed due to not seeing them in-game yet. This means people can start their localization process for the mod.

Do be aware that some of the text - especially the ones in the Intel panel(enemy orders like Attack, Patrol, Reinforce, Ammunition Supply etc,) - may go missing if you have a campaign in progress before this update is live. This is due to the fact such information is saved in file, and in order to localize them, I had to make changes in the corresponding code, resulting in the text not being read. 
This does **NOT** affect the actual order of the enemy, only causes existing text to disappear, and as time goes on, newly created AI orders will eventually catch up and show up correctly. 
That being said, a fresh start will ensure everything is showing properly.

**Comment by Sparker95** [comment]
Thanks a lot for your works, that's really outstanding!

Regarding the issue, it's not great that it happens. I think what we should try to do is something like this:
try to localize the text
if it's not localized, use the default value from the code
We don't want to break data between saved games. From your description it seems that it only affects the intel names, right?

**Comment by Sparker95** [comment]
I've checked it briefly and I think that we can merge it!

Only one imperfection I can't pass by:
In situations like this:
https://github.com/nercon/Vindicta/blob/e30dfba21ec314756b17212185dd874264931af5/src/Dialogue/Dialogues/DialogueCivilian.sqf#L83-L86
We don't want to localize every single string to store it into array. We would rather store stringtable entries, then when we want to pick up a random sentence:
https://github.com/nercon/Vindicta/blob/e30dfba21ec314756b17212185dd874264931af5/src/Dialogue/Dialogues/DialogueCivilian.sqf#L138
we should instead do `localize (selectRandom ...)` so that we don't have to type `localize` a million of times.

But since it's already done this way we can leave it as it is. I've checked and it doesn't seem to have any significant performance load if we ask the game to localize 20 strings at once.

**Pull request merged**
