### PR TITLE
New Factions WW II

### PR DESCRIPTION
**Pull request by MatrikSky**
**Those are four new WW2 factions including Germany and UK. In the future I will be making new factions such as USSR and US, for now i official announce that those two factions are 99% complete only needing to write CfgPatches in them. They work fine with only two small bugs that I encountered, while play-testing them. Sorry to say but the small amount of time that I have (because of High School ) will delay the progress on USSR (around 16% complete) and US (haven't even started) factions.** 

**- WW2_Heer,**      
//Done
//Still has some other bugs #306 
**- WW2_Heer (Police),**      
//Done        
//Still has some bugs #306 
**- WW2_UK,**      
//Done        
//Still has some bugs #306 
**- WW2_UK (Police),**      
//Done        
//Still has some bugs #306

**WW II factions will need a couple of mods so I have made a collection just for you.**
https://steamcommunity.com/sharedfiles/filedetails/?id=1980236949

Factions made by **MatrikSky**

### CODE REVIEW

**Comment by Sparker95** [comment]
Thanks man. Now the interesting part: you need to list them here:
https://github.com/Sparker95/Vindicta/blob/development/Vindicta.Altis/Templates/initFactions.sqf
And see how many errors our validation tool will find.

**Comment by MatrikSky** [comment]
So where will be the errors enlisted?

**Comment by Sparker95** [comment]
If you click 'details' next to 'some checks have failed', you can see them. If you install vscode you will be able to see them in vscode too.

**Comment by MatrikSky** [comment]
Well it seems that all checks have failed XD. So what do i do now to fix the errors?

**Comment by MatrikSky** [comment]
Sparker do you know what may be causing that error ?

**Comment by MatrikSky** [comment]
Yes finely

**Comment by MatrikSky** [comment]
Required PBOs

"ww2_assets_c_characters_americans_c.pbo", "ww2_assets_c_characters_british_c.pbo", "ww2_assets_c_characters_civilians_c.pbo", "ww2_assets_c_characters_core_c.pbo", "ww2_assets_c_characters_customfaces_c.pbo", "ww2_assets_c_characters_headgear_c.pbo", "ww2_assets_c_characters_polish_c.pbo", "ww2_assets_c_characters_searchanddestroy_c.pbo", "ww2_assets_c_characters_soviets_c.pbo"

**Comment by kju** [comment]
thanks a lot @MatrikSky for the IFA3 support!

**Comment by MatrikSky** [comment]
Seams that after RHSGREF update on the January 20 broke the HIDF faction. (probably they have changed classnames of units and equipment)

**Comment by MatrikSky** [comment]
I won't bother fixing HIDF faction because it will be used as template by Sebastian when RHS adds Vietnam era equipment. Keep that in mind its simple template not meant to be used at this state of its development.

**Pull request closed without merging**
