### PR TITLE
Police Update

### PR DESCRIPTION
**Pull request by MatrikSky**

### CODE REVIEW

**Comment by Sparker95** [comment]
Just writing it here so I don't forget what it is about:
Police factions are branched into DLC and standard factions.

**Comment by Sparker95** [comment]
It throws lots of errors for me while processing the faction, because class weights are specified in interleaved format like `class name, chance, class name, chance, ...`.
I didn't add support for that format, but I thought that @billw2012 did?

**Comment by Sparker95** [comment]
Also, PLEASE PLEASE look into the rpt file yourself next time.

**Comment by MatrikSky** [comment]
> It throws lots of errors for me while processing the faction, because class weights are specified in interleaved format like `class name, chance, class name, chance, ...`.
> I didn't add support for that format, but I thought that @billw2012 did?

I asked bill couple weeks ago if there is a chance implemented for factions spawning. He answered yes and told me to use `class name, chance, class name, chance...` format, also I looked in the RPT file and apparently I haven't seen any errors with the factions? From my play testing I saw the class weights are working because spawning chance of an AR armed police officer are significantly lower than the normal officer with the handgun.

I will double check the RPT file in case I missed something and fix it if I have.

**Comment by MatrikSky** [comment]
Ok so apparently i haven't noticed the errors :/ from what I can see this class weights format is a problem I don't get it why isn't it working if it's a supported format, civilian factions use it without any problems. For reference WW2 Civs'"LIB_GazM1", 8, "LIB_GazM1_dirty", 7, "LIB_FRA_CitC4", 4, "LIB_FRA_CitC4Ferme", 1'

**Comment by MatrikSky** [comment]
I can always rework the files to the old and awfuly looking format `"Arma3_police_officer" "Arma3_police_officer" "Arma3_police_14" "Arma3_police_14" "Arma3_police_14" "Arma3_police_13" "Arma3_police_13" "Arma3_police_13"...` let me know if it's a good idea @Sparker95 ❤️

**Comment by Sparker95** [comment]
Leave it as it is for now, I will have to see what's going on.
Civilian factions are a different thing.

**Comment by Sparker95** [comment]
I have had a look and I think I have resolved the issue with the staggered unit subcategory format. Could you remake this pull request please?

**Comment by Sparker95** [comment]
I wanted to try to migrate those files myself but it says that your repository is private unfortunately.

**Pull request closed without merging**
