### PR TITLE
Fix and edit arsenal behaviour 

### PR DESCRIPTION
**Pull request by Jeroen-Notenbomer**
- Right tab in arsenal doesnt get set back to default after switching weapon, uniform, vest or backpack
- Fixed some errors in load loadout function that caused a lot of spam in RPT

### CODE REVIEW

**Comment by Sparker95** [comment]
Nice, thanks a lot Jeroen, merge when ready.

**Comment by Jeroen-Notenbomer** [comment]
Could you check what problem you had with backpacks? I think you meant that it switched back to the first tab on the left side, but I'm not sure. If that is the case this pull request should remove that behavior.

**Comment by Sparker95** [comment]
I don't remember at all, I only remember that I had a backpack with items and I switched to backpack tab, then clicked something and had errors appear on my screen, sorry.

**Comment by Sparker95** [comment]
Let's merge it then?

**Pull request merged**
