### PR TITLE
Added try_lock_for mutex, applied to save message loops

### PR DESCRIPTION
**Pull request by billw2012**
Untested as yet

### CODE REVIEW

**Comment by billw2012** [comment]
Partially addresses #301.

**Comment by Sparker95** [comment]
I fixed the typos and it seems to be working. Need to test what happens if I set unrealistic timeouts I guess.

**Comment by Sparker95** [comment]
If I set timeout to 0 then it seems to behave as it should:
```
 0:58:50 "Locking thread messageLoopGameMode, this could take up to 0 seconds -- be patient"
 0:58:50 "Locking thread messageLoopCommanderEast, this could take up to 0 seconds -- be patient"
 0:58:50 "Locking thread messageLoopCommanderWest, this could take up to 0 seconds -- be patient"
 0:58:50 "Locking thread messageLoopCommanderInd, this could take up to 0 seconds -- be patient"
 0:58:50 "Warning: failed to lock message loop messageLoopCommanderInd in reasonable time, saving anyway."
 0:58:50 "Locking thread messageLoopMain, this could take up to 0 seconds -- be patient"
 0:58:50 "Locking thread messageLoopGroupAI, this could take up to 0 seconds -- be patient"
```
I guess we can merge it if we really want...

**Comment by billw2012** [comment]
Well we should definitely merge it unless you have a better fix? Being unable to save is a catastrophic problem in my book.

**Comment by Sparker95** [comment]
Right now I don't have any other fix, that would be my next thing after the broken respawn menu, so let's merge it?

**Comment by billw2012** [comment]
Sure, I can do the thread restart work as well if you want, just want something in asap for this problem.

**Comment by Sparker95** [comment]
Ok if you want it now I can push it, I just don't like to rush things, might break something else with sqf but let's see.

**Comment by billw2012** [comment]
lol I tried to merge at same time as you.... hope it is not confused

**Pull request merged**
