### PR TITLE
ACRE Support

### PR DESCRIPTION
**Pull request by TahMahn**
Added a way for the script to detect if ACRE is loaded, then add radios/antennas from ACRE to the loot pool. Worked fine playing around solo for a lil'bit, will likely need more testing to be sure of course.

Do let me know if I've fucked up, kinda new to this whole Pull Request thing.

### CODE REVIEW

**Comment by TahMahn** [comment]
Awesome! No problem! And thanks :D 

Stay cool dudes. <3

**Comment by Sparker95** [comment]
Hi! Thanks for the PR. Can you check the errors again? The validation has failed, but it seems to point at some error somewhere in Unit.sqf.

**Comment by Sparker95** [comment]
I will be tweaking loot soon I hope, then I will merge your branch as well.

**Comment by TahMahn** [comment]
For sure, I just had a brief glance at the error the appveyor threw. From what I understand it's pointing to an error at line 864 in unit.sqf file, which looks like this: `	} ENDMETHOD;`

And to be completely honest, I'm not sure what the error means. The file itself looks fine to my eyes, as I haven't touched anything besides adding the ACRE part.

Do you think it could be because it's inline with the ACE item section? I could try moving it just below that, above the lines that add vests and backpacks and see if that still throws and error.

**Comment by Sparker95** [comment]
A bracket was missing, now it's fine.

**Comment by TahMahn** [comment]
... boy do I feel silly.

Thanks man.

**Comment by Sparker95** [comment]
You were adding ACRE items within the `f (isClass (configfile >> "CfgPatches" >> "ace_common")) then {` statement btw

**Comment by Sparker95** [comment]
I have moved your code a bit so that ACRE radios are added to all vehicles instead of only cargo boxes.

**Comment by Sparker95** [comment]
We can merge it I think

**Pull request merged**
