### PR TITLE
Add ACE_Banana to arsenal

### PR DESCRIPTION
**Pull request by Chronophylos**

### CODE REVIEW

**Comment by Sparker95** [comment]
Hi!
We have an array of items which are common for all factions:
https://github.com/Sparker95/Vindicta/blob/b87287e45ba98daccb0383e0ef455644d43e0dac/Vindicta.Altis/Templates/Loot/items.sqf#L83
Perhaps we should add it here instead?

**Comment by Sparker95** [comment]
So you want to add one banana to each box? What's the purpose of banana anyway?

**Comment by Chronophylos** [comment]
Yes.
Bananas are bananas. Their purpose is being bananas.

I just thought it's funny to add the banana. Feel free to close the PR if you don't like it

**Comment by Sparker95** [comment]
I thought that they could be eaten to restore stamina or something like that, or am I wrong?

**Comment by Chronophylos** [comment]
No, they are completely useless

**Comment by Sparker95** [comment]
I'll add some bananas to `items.sqf`.

**Pull request closed without merging**
