### PR TITLE
Extra factions

### PR DESCRIPTION
**Pull request by shrimpee**
Altis Special Police Unit faction

### CODE REVIEW

**Comment by billw2012** [comment]
I want this, but with 2700 files marked changed its pretty hard to review! Any chance you could try merging latest master from us?

**Comment by zalexki** [comment]
@shrimpee can you remove all the changes done to the docs folder ? 
It will ease the review, thank you.

**Comment by Lazejun** [comment]
Looked over it, this is not in a working state:
Faction Template has a Double paste, misses Templatename inside.

Init files are missing Integration for Faction and Loadouts.

Loadouts also have a Double pace aswell.

Missing requieredmod (Altis SPU)

-------> Militarized Police with Spar16s (HK416s)

The files change spam looks like he faught the Githhub and the Github won.

**Comment by billw2012** [comment]
Oh the problem is merging from master, there shouldn't be any merges from master, development is our default stream. I suggest name a new branch from development, then either cherry pick your changes into it, or add them back manually. I can't accept this as is, it will make a mess of our repo.

**Comment by billw2012** [comment]
Not fixed in a timely manner, feel free to resubmit with the issues resolved.

**Pull request closed without merging**
