### PR TITLE
General Factions Update

### PR DESCRIPTION
**Pull request by MatrikSky**
**Changelog:**

- Updated UK and Germany vehicles
- Reworked vanilla Police faction (now it isn't boring with police using more of vanilla pistols and SMGs)  
- Added new custom units with FOW guns to German, UK. UK(police), SS(police) factions (greater range of weapons to choose from) 
- Added better faction description to WW2 factions (historical based)

### CODE REVIEW

**Comment by billw2012** [comment]
You removed review request just in time for me to notice it! You are doing more work on it or you want it reviewed as is?

**Comment by MatrikSky** [comment]
> You removed review request just in time for me to notice it! You are doing more work on it or you want it reviewed as is?

Grate timing I just made another update to it and now it's ready to be reviewed :)

**Comment by marvis999** [comment]
I unfortunately shortened descriptions for those presets, so they display properly in the new create game listbox. That's why there's conflicts.

What you can do is merge development into your branch, with VS code you can then manually accept my incoming changes. That should resolve the problems.

**Comment by marvis999** [comment]
I unfortunately shortened descriptions for those presets, so they display properly in the new create game listbox. That's why there's conflicts.

What you can do is merge development into your branch, with VS code you can then manually accept my incoming changes. That should resolve the problems.

**Pull request merged**
